import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;

public class GUI {
    User user;
    Database db;
    private JPanel BG;
    private JPanel leftJPanel;
    private JPanel rightJPanel;
    private JList<Object> alunosList;
    private JList<Object> profList;
    private JLabel nomeLabel;
    private JLabel cursoLabel;
    private JLabel roleLabel;
    private JLabel cpfLabel;
    private JLabel emailLabel;
    private JLabel idadeLabel;
    private JButton deleteButton;
    private JButton putButton;
    private JPanel buttonsJPanel;
    private JLabel profLabel;
    private JLabel alunoLabel;
    private JButton postButton;
    private JTextField nomeTx;
    private JTextField emailTx;
    private JTextField cpfTx;
    private JComboBox<String> cursoCombo;
    private JSpinner idadeSpinner;
    private JRadioButton alunoRadioButton;
    private JButton loadButton;
    private JRadioButton masculinoRadioButton;
    private JRadioButton femininoRadioButton;
    private JRadioButton outroRadioButton;
    private JLabel generoLabel;
    private JRadioButton professorRadioButton;
    private ButtonGroup genderGroup;
    private ButtonGroup roleGroup;

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        BG = new JPanel();
        BG.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        leftJPanel = new JPanel();
        leftJPanel.setLayout(new GridLayoutManager(8, 5, new Insets(0, 0, 0, 0), -1, -1));
        BG.add(leftJPanel, new GridConstraints(0, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        nomeLabel = new JLabel();
        nomeLabel.setText("Nome");
        nomeLabel.setToolTipText("Insira seu nome.");
        leftJPanel.add(nomeLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        emailLabel = new JLabel();
        emailLabel.setText("Email");
        emailLabel.setToolTipText("Insira seu email.");
        leftJPanel.add(emailLabel, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cpfLabel = new JLabel();
        cpfLabel.setText("CPF");
        cpfLabel.setToolTipText("11 caractéres no máximo, não precisa de pontuação.");
        leftJPanel.add(cpfLabel, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cursoLabel = new JLabel();
        cursoLabel.setBackground(new Color(-12236470));
        cursoLabel.setText("Curso");
        cursoLabel.setToolTipText("Selecione um curso.");
        leftJPanel.add(cursoLabel, new GridConstraints(6, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idadeLabel = new JLabel();
        idadeLabel.setText("Idade");
        idadeLabel.setToolTipText("De 18 a 100 anos.");
        leftJPanel.add(idadeLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        roleLabel = new JLabel();
        roleLabel.setText("Tipo De Usuário");
        roleLabel.setToolTipText("Escolha entre Aluno ou Professor (OBRIGATÓRIO)");
        leftJPanel.add(roleLabel, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        leftJPanel.add(spacer1, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, new Dimension(88, 11), null, 0, false));
        generoLabel = new JLabel();
        generoLabel.setText("Gênero");
        leftJPanel.add(generoLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        masculinoRadioButton = new JRadioButton();
        masculinoRadioButton.setSelected(true);
        masculinoRadioButton.setText("Masculino");
        leftJPanel.add(masculinoRadioButton, new GridConstraints(1, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nomeTx = new JTextField();
        leftJPanel.add(nomeTx, new GridConstraints(0, 2, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        idadeSpinner = new JSpinner();
        idadeSpinner.setToolTipText("");
        leftJPanel.add(idadeSpinner, new GridConstraints(2, 2, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        emailTx = new JTextField();
        leftJPanel.add(emailTx, new GridConstraints(3, 2, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cpfTx = new JTextField();
        leftJPanel.add(cpfTx, new GridConstraints(4, 2, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        alunoRadioButton = new JRadioButton();
        alunoRadioButton.setSelected(true);
        alunoRadioButton.setText("Aluno");
        leftJPanel.add(alunoRadioButton, new GridConstraints(5, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cursoCombo = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Administração");
        defaultComboBoxModel1.addElement("Análise e Desenvolvimento de Sistemas");
        defaultComboBoxModel1.addElement("Ciência da Computação");
        defaultComboBoxModel1.addElement("Ciências Contábeis");
        defaultComboBoxModel1.addElement("Design");
        defaultComboBoxModel1.addElement("Direito");
        defaultComboBoxModel1.addElement("Engenharia Civil");
        defaultComboBoxModel1.addElement("Engenharia da Computação");
        defaultComboBoxModel1.addElement("Engenharia de Produção");
        defaultComboBoxModel1.addElement("Engenharia Elétrica");
        defaultComboBoxModel1.addElement("Gestão de Recursos Humanos");
        defaultComboBoxModel1.addElement("Jornalismo");
        defaultComboBoxModel1.addElement("Logística");
        defaultComboBoxModel1.addElement("Marketing");
        defaultComboBoxModel1.addElement("Pedagogia");
        defaultComboBoxModel1.addElement("Publicidade e Propaganda");
        defaultComboBoxModel1.addElement("Redes de Computadores");
        cursoCombo.setModel(defaultComboBoxModel1);
        leftJPanel.add(cursoCombo, new GridConstraints(6, 2, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        postButton = new JButton();
        postButton.setBackground(new Color(-10640783));
        postButton.setText("CREATE");
        postButton.setToolTipText("Adiciona entrada ao banco.");
        leftJPanel.add(postButton, new GridConstraints(7, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        outroRadioButton = new JRadioButton();
        outroRadioButton.setText("Outro");
        leftJPanel.add(outroRadioButton, new GridConstraints(1, 4, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        femininoRadioButton = new JRadioButton();
        femininoRadioButton.setText("Feminino");
        leftJPanel.add(femininoRadioButton, new GridConstraints(1, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        professorRadioButton = new JRadioButton();
        professorRadioButton.setSelected(true);
        professorRadioButton.setText("Professor");
        leftJPanel.add(professorRadioButton, new GridConstraints(5, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rightJPanel = new JPanel();
        rightJPanel.setLayout(new GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        BG.add(rightJPanel, new GridConstraints(0, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        alunosList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        alunosList.setModel(defaultListModel1);
        rightJPanel.add(alunosList, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        buttonsJPanel = new JPanel();
        buttonsJPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rightJPanel.add(buttonsJPanel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        loadButton = new JButton();
        loadButton.setBackground(new Color(-16734554));
        loadButton.setEnabled(true);
        loadButton.setForeground(new Color(-8153962));
        loadButton.setText("LOAD");
        loadButton.setToolTipText("Carrega entrada escolhida na lista.");
        buttonsJPanel.add(loadButton);
        deleteButton = new JButton();
        deleteButton.setBackground(new Color(-3652048));
        deleteButton.setHideActionText(false);
        deleteButton.setText("DELETE");
        deleteButton.setToolTipText("Deleta entra selecionada na lista do banco.");
        buttonsJPanel.add(deleteButton);
        putButton = new JButton();
        putButton.setBackground(new Color(-14265220));
        putButton.setText("UPDATE");
        putButton.setToolTipText("Atualiza entrada seleciona da lista no banco.");
        buttonsJPanel.add(putButton);
        alunoLabel = new JLabel();
        alunoLabel.setText("Alunos No Banco");
        rightJPanel.add(alunoLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        profLabel = new JLabel();
        profLabel.setText("Professores No Banco");
        rightJPanel.add(profLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        profList = new JList();
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        profList.setModel(defaultListModel2);
        rightJPanel.add(profList, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        roleGroup = new ButtonGroup();
        roleGroup.add(alunoRadioButton);
        roleGroup.add(professorRadioButton);
        genderGroup = new ButtonGroup();
        genderGroup.add(masculinoRadioButton);
        genderGroup.add(femininoRadioButton);
        genderGroup.add(outroRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return BG;
    }

    public void setButtonsActions() {
        alunoRadioButton.setActionCommand("Alunos");
        professorRadioButton.setActionCommand("Professores");

        masculinoRadioButton.setActionCommand("Masculino");
        femininoRadioButton.setActionCommand("Feminino");
        outroRadioButton.setActionCommand("Outro");
    }

    public void updateLists(Database db) {
        DefaultListModel<Object> alunoListModel = new DefaultListModel<>();
        DefaultListModel<Object> profListModel = new DefaultListModel<>();

        ArrayList<String> profsGot = new ArrayList<>();
        ArrayList<String> alunosGot = new ArrayList<>();

        try {
            profsGot.addAll(db.entries("Professores"));
            alunosGot.addAll(db.entries("Alunos"));
        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            alunoListModel.addAll(alunosGot);
            profListModel.addAll(profsGot);
            alunosList.setModel(alunoListModel);
            profList.setModel(profListModel);
        }
    }

    public GUI(JFrame frame) {
        $$$setupUI$$$();
        db = new Database();
        setButtonsActions();
        updateLists(db);

        postButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                user = new User(nomeTx.getText(), genderGroup.getSelection().getActionCommand(), (int) idadeSpinner.getValue(), emailTx.getText(), String.valueOf(cursoCombo.getSelectedItem()), cpfTx.getText(), roleGroup.getSelection().getActionCommand());
                try {
                    db.post(user);
                    updateLists(db);
                } catch (SQLException exception) {
                    exception.printStackTrace();
                }
            }
        });

        loadButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });


        putButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
    }

    public static void main(String[] args) {
        Dimension screenRes = Toolkit.getDefaultToolkit().getScreenSize();
        JFrame frame = new JFrame("DBD - AV1");
        frame.setContentPane(new GUI(frame).BG);

        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setPreferredSize(new Dimension(1920 / 2, 1080 / 2));
        frame.setMinimumSize(new Dimension((int) screenRes.getWidth() / 2, (int) screenRes.getHeight() / 2));
        frame.setResizable(false);
        frame.pack();
        frame.setVisible(true);

    }


}
