import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;

public class GUI {
    private JPanel BG;
    private JPanel leftJPanel;
    private JPanel rightJPanel;
    private JList alunosList;
    private JList profList;
    private JLabel nomeLabel;
    private JLabel cursoLabel;
    private JLabel roleLabel;
    private JLabel cpfLabel;
    private JLabel emailLabel;
    private JLabel idadeLabel;
    private JButton deleteButton;
    private JButton putButton;
    private JPanel buttonsJPanel;
    private JLabel profLabel;
    private JLabel alunoLabel;
    private JButton postButton;
    private JTextField nomeTx;
    private JTextField emailTx;
    private JTextField cpfTx;
    private JComboBox cursoCombo;
    private JSpinner idadeSpinner;
    private JRadioButton professorRadioButton;
    private JRadioButton alunoRadioButton;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        BG = new JPanel();
        BG.setLayout(new GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        leftJPanel = new JPanel();
        leftJPanel.setLayout(new GridLayoutManager(8, 8, new Insets(0, 0, 0, 0), -1, -1));
        BG.add(leftJPanel, new GridConstraints(1, 0, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        nomeLabel = new JLabel();
        nomeLabel.setText("Nome");
        nomeLabel.setToolTipText("Insira seu nome.");
        leftJPanel.add(nomeLabel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nomeTx = new JTextField();
        leftJPanel.add(nomeTx, new GridConstraints(0, 2, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        emailTx = new JTextField();
        leftJPanel.add(emailTx, new GridConstraints(2, 2, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        emailLabel = new JLabel();
        emailLabel.setText("Email");
        emailLabel.setToolTipText("Insira seu email.");
        leftJPanel.add(emailLabel, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cpfTx = new JTextField();
        leftJPanel.add(cpfTx, new GridConstraints(3, 2, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        cpfLabel = new JLabel();
        cpfLabel.setText("CPF");
        cpfLabel.setToolTipText("11 caractéres no máximo, não precisa de pontuação.");
        leftJPanel.add(cpfLabel, new GridConstraints(3, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cursoCombo = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Administração");
        defaultComboBoxModel1.addElement("Análise e Desenvolvimento de Sistemas");
        defaultComboBoxModel1.addElement("Ciência da Computação");
        defaultComboBoxModel1.addElement("Ciências Contábeis");
        defaultComboBoxModel1.addElement("Design");
        defaultComboBoxModel1.addElement("Direito");
        defaultComboBoxModel1.addElement("Engenharia Civil");
        defaultComboBoxModel1.addElement("Engenharia da Computação");
        defaultComboBoxModel1.addElement("Engenharia de Produção");
        defaultComboBoxModel1.addElement("Engenharia Elétrica");
        defaultComboBoxModel1.addElement("Gestão de Recursos Humanos");
        defaultComboBoxModel1.addElement("Jornalismo");
        defaultComboBoxModel1.addElement("Logística");
        defaultComboBoxModel1.addElement("Marketing");
        defaultComboBoxModel1.addElement("Pedagogia");
        defaultComboBoxModel1.addElement("Publicidade e Propaganda");
        defaultComboBoxModel1.addElement("Redes de Computadores");
        cursoCombo.setModel(defaultComboBoxModel1);
        leftJPanel.add(cursoCombo, new GridConstraints(5, 2, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        cursoLabel = new JLabel();
        cursoLabel.setBackground(new Color(-12236470));
        cursoLabel.setText("Curso");
        cursoLabel.setToolTipText("Selecione um curso.");
        leftJPanel.add(cursoLabel, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idadeSpinner = new JSpinner();
        idadeSpinner.setToolTipText("");
        leftJPanel.add(idadeSpinner, new GridConstraints(1, 2, 1, 5, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        idadeLabel = new JLabel();
        idadeLabel.setText("Idade");
        idadeLabel.setToolTipText("De 18 a 100 anos.");
        leftJPanel.add(idadeLabel, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        roleLabel = new JLabel();
        roleLabel.setText("Tipo De Usuário");
        roleLabel.setToolTipText("Escolha entre Aluno ou Professor (OBRIGATÓRIO)");
        leftJPanel.add(roleLabel, new GridConstraints(4, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        alunoRadioButton = new JRadioButton();
        alunoRadioButton.setSelected(true);
        alunoRadioButton.setText("Aluno");
        leftJPanel.add(alunoRadioButton, new GridConstraints(4, 2, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        leftJPanel.add(spacer1, new GridConstraints(7, 1, 1, 7, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        leftJPanel.add(spacer2, new GridConstraints(0, 7, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        professorRadioButton = new JRadioButton();
        professorRadioButton.setSelected(false);
        professorRadioButton.setText("Professor");
        leftJPanel.add(professorRadioButton, new GridConstraints(4, 5, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer3 = new Spacer();
        leftJPanel.add(spacer3, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        postButton = new JButton();
        postButton.setBackground(new Color(-10640783));
        postButton.setText("CREATE");
        postButton.setToolTipText("Adiciona entrada ao banco.");
        leftJPanel.add(postButton, new GridConstraints(6, 4, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rightJPanel = new JPanel();
        rightJPanel.setLayout(new GridLayoutManager(6, 1, new Insets(0, 0, 0, 0), -1, -1));
        BG.add(rightJPanel, new GridConstraints(1, 1, 2, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        alunosList = new JList();
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        alunosList.setModel(defaultListModel1);
        rightJPanel.add(alunosList, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        buttonsJPanel = new JPanel();
        buttonsJPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rightJPanel.add(buttonsJPanel, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        deleteButton = new JButton();
        deleteButton.setBackground(new Color(-3652048));
        deleteButton.setHideActionText(true);
        deleteButton.setText("DELETE");
        deleteButton.setToolTipText("Deleta entra selecionada na lista do banco.");
        buttonsJPanel.add(deleteButton);
        putButton = new JButton();
        putButton.setBackground(new Color(-5264711));
        putButton.setText("UPDATE");
        putButton.setToolTipText("Atualiza entrada seleciona da lista no banco.");
        buttonsJPanel.add(putButton);
        alunoLabel = new JLabel();
        alunoLabel.setText("Alunos No Banco");
        rightJPanel.add(alunoLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer4 = new Spacer();
        rightJPanel.add(spacer4, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        profLabel = new JLabel();
        profLabel.setText("Professores No Banco");
        rightJPanel.add(profLabel, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        profList = new JList();
        final DefaultListModel defaultListModel2 = new DefaultListModel();
        profList.setModel(defaultListModel2);
        rightJPanel.add(profList, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
        final Spacer spacer5 = new Spacer();
        BG.add(spacer5, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(alunoRadioButton);
        buttonGroup.add(professorRadioButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return BG;
    }

    public GUI(JFrame frame) {

    }

    public static void main(String[] args) {
        Dimension screenRes = Toolkit.getDefaultToolkit().getScreenSize();
        JFrame frame = new JFrame("DBD - AV1");
        frame.setContentPane(new GUI(frame).BG);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setPreferredSize(new Dimension(1920 / 2, 1080 / 2));
        frame.setMinimumSize(new Dimension((int) screenRes.getWidth() / 2, (int) screenRes.getHeight() / 2));
        frame.setResizable(false);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
